#!/bin/zsh
keyboard=keychron/v8/ansi_encoder 
keymap=pxv.v8.01

echo 
echo "-----"
echo Keyboard: $keyboard
echo Keymap: $keymap
echo Option: $1
echo 
echo "Continue?"
read 
if [ $REPLY != "y" ]; then
    exit
fi

if [ $# -ne "1" ]; then 
    echo 'Requires "compile", "flash", or "both"'
fi

if [ $1 = "compile" ]; then 
    qmk compile -kb $keyboard -km $keymap
    echo "Compiled"
fi

if [ $1 = "flash" ]; then 
    qmk flash -kb $keyboard -km $keymap
    echo "Flashed"
fi

if [ $1 = "both" ]; then
    echo "Compile then flash"
    qmk compile -kb $keyboard -km $keymap
    qmk flash -kb $keyboard -km $keymap
fi

